-- ============================================================
-- Data warehouse - dimensional model (fact constellation)
--
-- Two fact tables sharing conformed dimensions:
--
--   fact_ventas             grain: one order line
--   fact_llamadas_servicio  grain: one call to the service center
--
-- Conformed dimensions (used by both facts): dim_tiempo, dim_cliente,
-- dim_producto. Customers and products share the same business key in
-- both sources, which is what allows the two facts to be combined.
--
-- The staging layers of the ETL are defined in 02_staging_layers.sql
-- and the data-mart views in 03_data_marts.sql.
-- ============================================================

DROP TABLE IF EXISTS fact_ventas             CASCADE;
DROP TABLE IF EXISTS fact_llamadas_servicio  CASCADE;
DROP TABLE IF EXISTS dim_tiempo              CASCADE;
DROP TABLE IF EXISTS dim_cliente             CASCADE;
DROP TABLE IF EXISTS dim_producto            CASCADE;
DROP TABLE IF EXISTS dim_empleado            CASCADE;
DROP TABLE IF EXISTS dim_oficina             CASCADE;
DROP TABLE IF EXISTS dim_estado_orden        CASCADE;

-- ------------------------------------------------------------
-- Conformed dimensions
-- ------------------------------------------------------------

-- Generated by the ETL, not extracted. The surrogate key is the date
-- as YYYYMMDD.
CREATE TABLE dim_tiempo (
    tiempo_key      INTEGER PRIMARY KEY,
    fecha           DATE        NOT NULL UNIQUE,
    anio            SMALLINT    NOT NULL,
    trimestre       SMALLINT    NOT NULL,
    mes             SMALLINT    NOT NULL,
    nombre_mes      VARCHAR(12) NOT NULL,
    dia             SMALLINT    NOT NULL,
    dia_semana      SMALLINT    NOT NULL,   -- 1 = Monday, 7 = Sunday
    nombre_dia      VARCHAR(12) NOT NULL,
    es_fin_semana   BOOLEAN     NOT NULL,
    anio_mes        CHAR(7)     NOT NULL    -- '2003-01', monthly grouping key
);

-- Customer, conformed across both sources. direccion_completa merges
-- addressLine1 and addressLine2 (the latter is null in 81.97% of rows).
CREATE TABLE dim_cliente (
    cliente_key             SERIAL PRIMARY KEY,
    numero_cliente          INTEGER NOT NULL UNIQUE,   -- business key
    nombre_cliente          VARCHAR(100),
    contacto_nombre         VARCHAR(100),
    contacto_apellido       VARCHAR(100),
    telefono                VARCHAR(50),
    direccion_completa      VARCHAR(220),
    ciudad                  VARCHAR(100),
    estado_region           VARCHAR(100),
    codigo_postal           VARCHAR(20),
    pais                    VARCHAR(100),
    limite_credito          NUMERIC(12,2),
    presente_en_ventas      BOOLEAN NOT NULL DEFAULT FALSE,
    presente_en_servicio    BOOLEAN NOT NULL DEFAULT FALSE
);

-- Product, conformed across both sources, with its product line
-- denormalised from productlines. Only textDescription is kept:
-- htmlDescription and image are 100% null in the source.
CREATE TABLE dim_producto (
    producto_key            SERIAL PRIMARY KEY,
    codigo_producto         VARCHAR(20) NOT NULL UNIQUE,   -- business key
    nombre_producto         VARCHAR(140),
    linea_producto          VARCHAR(60),
    descripcion_linea       TEXT,
    escala                  VARCHAR(20),
    proveedor               VARCHAR(100),
    precio_compra           NUMERIC(12,2),
    precio_msrp             NUMERIC(12,2),
    presente_en_ventas      BOOLEAN NOT NULL DEFAULT FALSE,
    presente_en_servicio    BOOLEAN NOT NULL DEFAULT FALSE
);

-- ------------------------------------------------------------
-- Non-conformed dimension
--
-- Sales reps (classicmodels.employees, 23 rows) and call-center agents
-- (customerservice.cs_employees, 30 rows) are different people with no
-- shared key. Both populations live in one dimension under the
-- composite business key (numero_empleado, sistema_origen).
-- ------------------------------------------------------------
CREATE TABLE dim_empleado (
    empleado_key        SERIAL PRIMARY KEY,
    numero_empleado     INTEGER     NOT NULL,
    sistema_origen      VARCHAR(20) NOT NULL,   -- 'classicmodels' | 'customerservice'
    nombre              VARCHAR(100),
    apellido            VARCHAR(100),
    email               VARCHAR(140),
    cargo               VARCHAR(80),
    numero_oficina      VARCHAR(20),
    UNIQUE (numero_empleado, sistema_origen)
);

-- ------------------------------------------------------------
-- Dimensions that only exist in classicmodels
-- ------------------------------------------------------------

CREATE TABLE dim_oficina (
    oficina_key     SERIAL PRIMARY KEY,
    codigo_oficina  VARCHAR(20) NOT NULL UNIQUE,
    ciudad          VARCHAR(100),
    pais            VARCHAR(100),
    region          VARCHAR(100),
    territorio      VARCHAR(20)
);

-- es_efectiva is FALSE for Cancelled, Disputed and On Hold, so reports
-- can exclude those orders without removing them from the warehouse.
CREATE TABLE dim_estado_orden (
    estado_key      SERIAL PRIMARY KEY,
    estado          VARCHAR(30) NOT NULL UNIQUE,
    es_efectiva     BOOLEAN     NOT NULL
);

-- ------------------------------------------------------------
-- fact_ventas - grain: one order line.
-- Fed by orderdetails, orders, products, customers and employees
-- (classicmodels).
-- ------------------------------------------------------------
CREATE TABLE fact_ventas (
    venta_key           BIGSERIAL PRIMARY KEY,

    -- Dimension keys
    tiempo_key          INTEGER NOT NULL REFERENCES dim_tiempo(tiempo_key),
    cliente_key         INTEGER NOT NULL REFERENCES dim_cliente(cliente_key),
    producto_key        INTEGER NOT NULL REFERENCES dim_producto(producto_key),
    empleado_key        INTEGER          REFERENCES dim_empleado(empleado_key),
    oficina_key         INTEGER          REFERENCES dim_oficina(oficina_key),
    estado_key          INTEGER NOT NULL REFERENCES dim_estado_orden(estado_key),

    -- Degenerate dimensions (source identifiers).
    numero_orden        INTEGER  NOT NULL,
    numero_linea        SMALLINT NOT NULL,

    -- Measures
    cantidad_ordenada   INTEGER       NOT NULL,   -- additive
    precio_unitario     NUMERIC(12,2) NOT NULL,   -- non-additive (average it)
    monto_linea         NUMERIC(14,2) NOT NULL,   -- additive: quantity * price
    costo_linea         NUMERIC(14,2),            -- additive: quantity * buy price
    margen_linea        NUMERIC(14,2),            -- additive: amount - cost
    precio_msrp         NUMERIC(12,2),            -- non-additive
    dias_hasta_envio    SMALLINT,                 -- semi-additive; NULL if not shipped

    UNIQUE (numero_orden, numero_linea)
);

-- ------------------------------------------------------------
-- fact_llamadas_servicio - grain: one service call.
-- Fed by cs_customer_calls (customerservice).
-- ------------------------------------------------------------
CREATE TABLE fact_llamadas_servicio (
    llamada_key         BIGSERIAL PRIMARY KEY,

    tiempo_key          INTEGER NOT NULL REFERENCES dim_tiempo(tiempo_key),
    cliente_key         INTEGER NOT NULL REFERENCES dim_cliente(cliente_key),
    producto_key        INTEGER NOT NULL REFERENCES dim_producto(producto_key),
    empleado_key        INTEGER NOT NULL REFERENCES dim_empleado(empleado_key),

    texto_llamada       TEXT,                     -- degenerate dimension

    cantidad_llamadas   SMALLINT NOT NULL DEFAULT 1,   -- additive
    longitud_texto      INTEGER                        -- additive
);

-- ------------------------------------------------------------
-- Foreign-key indexes (PostgreSQL does not create them automatically).
-- ------------------------------------------------------------
CREATE INDEX idx_fv_tiempo   ON fact_ventas(tiempo_key);
CREATE INDEX idx_fv_cliente  ON fact_ventas(cliente_key);
CREATE INDEX idx_fv_producto ON fact_ventas(producto_key);
CREATE INDEX idx_fv_empleado ON fact_ventas(empleado_key);
CREATE INDEX idx_fv_oficina  ON fact_ventas(oficina_key);
CREATE INDEX idx_fv_estado   ON fact_ventas(estado_key);

CREATE INDEX idx_fl_tiempo   ON fact_llamadas_servicio(tiempo_key);
CREATE INDEX idx_fl_cliente  ON fact_llamadas_servicio(cliente_key);
CREATE INDEX idx_fl_producto ON fact_llamadas_servicio(producto_key);
CREATE INDEX idx_fl_empleado ON fact_llamadas_servicio(empleado_key);
